### ISSUE TITLE
tidyAML  in the README Example: only 24 predictions output - mtcars has 32 rows ?

### ISSUE THREAD

**Issue by sfd99** [spsanderson/tidyAML#126]
**_Hi Steven,_**

tidyAML
sounds like a real time-saving idea.

**Q:**
in the  GIT README file example,
you mention:
    "Let’s look at the fitted workflow predictions...".
 
The example shows 24 mpg predictions 
in the output for each model in:
  - frt_tbl$pred_wflw

But doesn't mtcars have 32 rows (cars)?

Hope you can guide me here, Steven.
Really want to understand 
how to use tidyAML ,
in the simplest possible terms :-).

**SFd99
San Francisco
Linux, Rstudio
latest tidyAML PKG f/CRAN.**

**Comment by sfd99** [comment]
> If you look all the way, at the bottom of the read me, you’ll see that model number two has no prediction results. That’s the one that failed for the internal fit workflow model. The fitting process is wrapped around inside of purrr safely so that if it fails the rest of the models, can be continued to be fi

Ah, thanks Steven!.
Yes, 
I discovered the 2nd "NULL" later...
sorry about that.

My remaining Q: 
(if I may)

tidyAML in the README example: 

only 24 prediction results 
are shown for: mpg ,
But doesn't mtcars has 32 rows ?.

SFd99

**Comment by spsanderson** [comment]
I think you raise a good question that actually calls for a blog post, so thank you for that. To answer in short it is the testing set that is being predicted on, so this sounds like some new functionality is in order and some tweakingSent from my iPhonewww.spsanderson.comOn Feb 21, 2023, at 8:20 AM, sfd99 ***@***.***> wrote:﻿

If you look all the way, at the bottom of the read me, you’ll see that model number two has no prediction results. That’s the one that failed for the internal fit workflow model. The fitting process is wrapped around inside of purrr safely so that if it fails the rest of the models, can be continued to be fi

Ah, thanks Steven!.
Yes,
I discovered the 2nd "NULL" later...
sorry about that.
My remaining Q:
(if I may)
tidyAML in the README example:
only 24 prediction results
are shown for: mpg ,
But doesn't mtcars has 32 rows ?.
SFd99
