### ISSUE TITLE
Add dependencies to Suggests:

### ISSUE THREAD

**Issue by HenrikBengtsson** [spsanderson/tidyAML#147]
I saw your Fediverse post. Regardless of decision, I think you should declare all those extra package dependencies:

https://github.com/spsanderson/tidyAML/blob/98421368751dae4fdab09446555fb086da0d61a3/R/utils-lib-loads.R#L25-L31

under `Suggests:` in your DESCRIPTION file, if there's code in your package that depends on them.

My $.02

**Comment by spsanderson** [comment]
I can list them as suggests possibly because the package works without them, the models just safely fail.Sent from my iPhonewww.spsanderson.comOn May 26, 2023, at 3:37 PM, Henrik Bengtsson ***@***.***> wrote:﻿
I saw your Fediverse post. Regardless of decision, I think you should declare all those extra package dependencies:
https://github.com/spsanderson/tidyAML/blob/98421368751dae4fdab09446555fb086da0d61a3/R/utils-lib-loads.R#L25-L31
under Suggests: in your DESCRIPTION file, if there's code in your package that depends on them.
My $.02

**Comment by HenrikBengtsson** [comment]
A common expectation is that if you install and package and all of its declared dependencies, including suggested ones, then everything in the packages works. You should not have to install additional packages beyond this. This also makes reverse packages  checks possible plus more.
